name: Build and test Azure Functions

on:
  push:
    branches: [main]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build info
      run: |
        echo ::notice::"Build started"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: "WeatherApp/WeatherApp.AzureFunctions"
      run: dotnet restore
  
    - name: Format source
      continue-on-error: true
      working-directory: "WeatherApp/WeatherApp.AzureFunctions"
      run: dotnet format --verify-no-changes

    - name: Release source
      working-directory: "WeatherApp/WeatherApp.AzureFunctions"
      run: dotnet publish --no-restore --output output

    - name: Archive deploy package
      uses: actions/upload-artifact@v4
      with:
        name: deploy-package
        path: "WeatherApp/WeatherApp.AzureFunctions/output"
        retention-days: 30
        
    - name: Deploy info
      run: echo ::notice::"Deploy started"

#    - name: Deploy to Azure
#      uses: Azure/functions-action@v1.4.7
#      with:
#        app-name: "af-weatherapp-dev"
#        package: "WeatherApp/WeatherApp.AzureFunctions/output"
#        publish-profile: ${{ secrets.PUBLISH_CRED }}

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E296B19E68E14D76BEF0E8B6F40254BE }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_23B7AE4241B1419AA88B143C6DBEE07F }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6C49242A2FF64EA0AFF643EC78BEF2D8 }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'af-weatherapp-dev'
        slot-name: 'Production'
        package: 'WeatherApp/WeatherApp.AzureFunctions/output'
          
