name: Build and test Azure Functions

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build info
      run: |
        echo ::notice::"Build started"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: "/$WeatherApp"
      run: dotnet restore
  
    - name: Format source
      continue-on-error: true
      working-directory: "./$WeatherApp"
      run: dotnet format --verify-no-changes

    - name: Release source
      working-directory: "./$WeatherApp/WeatherApp.AzureFunctions"
      run: dotnet publish --no-restore --output output

    - name: Archive deploy package
      uses: actions/upload-artifact@v4
      with:
        name: deploy-package
        path: "./$WeatherApp/WeatherApp.AzureFunctions/output"
        retention-days: 30
        
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy info
      run: echo ::notice::"Deploy started"

    - name: Download deploy package
      uses: actions/download-artifact@v3
      with:
        name: deploy-package
        path: "output"

    - name: Deploy to Azure
      uses: Azure/functions-action@v1.4.7
      with:
        app-name: "af-weatherapp-dev"
        package: "output"
        publish-profile: ${{ secrets.PUBLISH_CRED }}
